version: '3'

services:
  quilc:
    image: rigetti/quilc:1.23.0
    command: -S
    expose:
      - "5555"
    ports:
    - '5555:5555'
    networks:
      - test

  qvm:
    image: rigetti/qvm:1.17.1
    command: -S
    expose:
      - "5000"
    ports:
    - '5000:5000'
    networks:
      - test

networks:
  test:
    driver: bridge

