apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: cirq-pr-monitor
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: us-docker.pkg.dev/cirq-infra/cirq/pr_monitor
    docker:
      dockerfile: pr_monitor/Dockerfile
    context: dev_tools
deploy:
  kubectl:
    manifests:
    - dev_tools/pr_monitor/statefulset.yaml
